=== A-Petersen/DartTest/docs/LevelShema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Game">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Level" type="Level" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		<xs:complexType name="Level">
		<xs:sequence>
			<xs:element name="Number" type="xs:int"/>
			<xs:element name="FruitsAmount" type="xs:int"/>
			<xs:element name="FruitRange" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>	
	
</xs:schema>

=== A-Petersen/DartTest/web/Level.xml
<?xml version="1.0" encoding="UTF-8"?>
<Game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LevelShema.xsd">
	<Level>
		<Number>1</Number>
		<FruitsAmount>3</FruitsAmount>
		<FruitRange>1</FruitRange>
	</Level>
	<Level>
		<Number>2</Number>
		<FruitsAmount>4</FruitsAmount>
		<FruitRange>2</FruitRange>
	</Level>
	<Level>
		<Number>3</Number>
		<FruitsAmount>5</FruitsAmount>
		<FruitRange>3</FruitRange>
	</Level>
</Game>
